version: "3"

services:
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
    volumes:
      - ./node_modules:/app/node_modules
      - ./src:/app/src
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=mydb
    command: npm run start:dev


  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=mydb

